sudo: required
before_script: chmod 0777 ./node_modules/.bin/mocha
language: node_js
node_js:
  - "stable"
services:
  - docker
deploy:
  skip_cleanup: true
  provider: script
  script: bash docker_push
  on:
    branch: master